//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ПракБД
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Название_цеха { get; set; }
        public Nullable<System.DateTime> Дата_поступления_на_работу { get; set; }
    }
}
